"""
Generate the Windows version resource for the built executable.

Windows shows these fields in the file's Properties > Details tab, and both
SmartScreen and antivirus reputation systems read them: an executable with no
company, no product name and no version looks exactly like something thrown
together, which is precisely the reputation problem this app already has.

Generated rather than hand-written so it can never drift from core/version.py.
Run from the repository root:  python packaging/make_version_info.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from core.version import APP_NAME, __version__  # noqa: E402

# Update these before a public release.
COMPANY = APP_NAME
DESCRIPTION = "Application usage tracker and limiter"
COPYRIGHT = "Copyright (C) 2026"

OUTPUT = Path(__file__).parent / "version_info.txt"

_TEMPLATE = """\
# Generated by packaging/make_version_info.py -- do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({v0}, {v1}, {v2}, 0),
    prodvers=({v0}, {v1}, {v2}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{company}'),
         StringStruct('FileDescription', '{description}'),
         StringStruct('FileVersion', '{version}'),
         StringStruct('InternalName', '{app}'),
         StringStruct('LegalCopyright', '{copyright}'),
         StringStruct('OriginalFilename', '{app}.exe'),
         StringStruct('ProductName', '{app}'),
         StringStruct('ProductVersion', '{version}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def parts(version: str):
    """Version as three integers, padded if it has fewer components."""
    numbers = [int(p) for p in version.split(".")[:3] if p.isdigit()]
    while len(numbers) < 3:
        numbers.append(0)
    return numbers


def render(version: str = __version__) -> str:
    v0, v1, v2 = parts(version)
    return _TEMPLATE.format(
        v0=v0, v1=v1, v2=v2,
        version=version,
        app=APP_NAME,
        company=COMPANY,
        description=DESCRIPTION,
        copyright=COPYRIGHT,
    )


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT} for {APP_NAME} {__version__}")


if __name__ == "__main__":
    main()
